# 🛠 Linear Algebra in Python
# This notebook contains hands-on examples of vectors, matrices, and linear algebra operations using NumPy.


In [1]:
import numpy as np

In [2]:
# --- 1️⃣ Vectors ---
v = np.array([1, 2, 3])
print("Vector v:", v)

Vector v: [1 2 3]


In [3]:
# --- 2️⃣ Vector Operations ---
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [4]:
print("v1 + v2:", v1 + v2)
print("v2 - v1:", v2 - v1)
print("Scalar multiplication 3 * v1:", 3 * v1)

v1 + v2: [5 7 9]
v2 - v1: [3 3 3]
Scalar multiplication 3 * v1: [3 6 9]


In [5]:
# --- 3️⃣ Dot Product ---
dot = np.dot(v1, v2)
print("Dot product of v1 and v2:", dot)

Dot product of v1 and v2: 32


In [6]:
# --- 4️⃣ Matrices ---
A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2]
 [3 4]]


In [7]:
# --- 5️⃣ Matrix Operations ---
B = np.array([[5, 6], [7, 8]])
print("A + B:\n", A + B)
print("B - A:\n", B - A)

A + B:
 [[ 6  8]
 [10 12]]
B - A:
 [[4 4]
 [4 4]]


In [8]:
# Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication (A.B):\n", C)

Matrix multiplication (A.B):
 [[19 22]
 [43 50]]


In [9]:
# --- 6️⃣ Transpose of a Matrix ---
print("Transpose of A:\n", A.T)

Transpose of A:
 [[1 3]
 [2 4]]


In [10]:
# --- 7️⃣ Determinant and Inverse ---
det = np.linalg.det(A)
inv = np.linalg.inv(A)
print("Determinant of A:", det)
print("Inverse of A:\n", inv)

Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
# --- 8️⃣ Identity and Zero Matrices ---
I = np.eye(3)  # 3x3 identity
Z = np.zeros((2, 3))  # 2x3 zero matrix
print("Identity Matrix 3x3:\n", I)
print("Zero Matrix 2x3:\n", Z)


Identity Matrix 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix 2x3:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# --- 9️⃣ Solving Linear Systems ---
A_sys = np.array([[3, 1], [1, 2]])
b_sys = np.array([9, 8])
x = np.linalg.solve(A_sys, b_sys)
print("Solution of linear system Ax=b:", x)

Solution of linear system Ax=b: [2. 3.]
